# product_dao_stubs.py
# France Cheong
# 11/12/2018

# Import packages
# From file xxx.py import class Xxxx
# Note: Filenames with hyphens cannot be imported, use underscores
from schema import Staff
"""
    #DAO class to perform basic operations on the staff table in the database.
"""
class StaffDAO():
    """
 This function creates staff by inserting data to linked variables 

    """
    def create(self, session, data):
        
        # Print info for debugging
        print("\nCreating staff ...") #\n means print("\n") a blank line
        print(data)

        # Instantiate an object of the mapped Employee class - defined in schema.py
        # SKip the employee_id when inserting as it will be generated by the database
        staff = Staff(first_name = data['first_name'], 
                    last_name = data['last_name'], 
                    title = data['title'],
                    sex = data['sex'], 
                    email = data['email'],
                    contact_no = data['contact_no']
                    )

        # Get the session to add the staff object
        session.add(staff)
        session.commit() # Must commit to save the record permanently

        # Create a blank dictionary to return the result
        result = {}  
        result['message'] = 'Staff added successfully!'
        inserted_staff_id = staff.staff_id
        result['staff_id'] = inserted_staff_id

        return result # return the result as a dictionary

    """
    This function find staff by searching for the requested staff_id 
    """ 
    def find_by_id(self, session, staff_id):
        
        # Print info for debugging
        print("\nFinding staff ...")
        print(staff_id)

        # Get the session to query the Employee class
        # And get by the primary key i.e. employee_id
        emp = session.query(Staff).get(staff_id) 
        
        # Create a blank dictionary to return the result
        result = {}

        # emp is a single Alchemy object - no need for a loop to process
        if not emp:
            # If no staff found i.e. emp is none
            result['message'] = "Staff NOT found"
        else:
            # Else grab the values in the returned SQLalchemy object
            # And build another python dictionary
            d = {} # Create an empty dict and add items to it
            d['staff_id'] = emp.staff_id # include the employee_id
            d['first_name'] = emp.first_name
            d['last_name'] = emp.last_name
            d['title'] = emp.title
            d['sex'] = emp.sex
            d['email'] = emp.email
            d['contact_no'] = emp.contact_no

            # Store the staff dict in the result dict under key "staff"
            result['staff'] = d
            #session.commit() # not needed for find as not saving changes            
        
        # Note that the return is not part of the if/else block
        # Ensure it's indented to the left
        return result # return the result as a dictionary

    """
    This function finds all staff available in the database
    """
    def find_all(self, session):
       
        # Print info for debugging
        print("\nFinding all employees ...")

        # Create a blank dictionary to return the result
        result = {}

        # Get the session to query the Employee class and get all (may wish to sort)
        rows = session.query(Staff).all()

        if not rows:
            result['message'] = "No staff found!"
        else:
            # Convert list of Alchemy objects to a list of dictionaries
            list_emp = [] # Create an empty list to append staff dicts
            for x in rows: # rows is a list of Alchemy objects - process one by one
                d = {} # Create an empty dict and add items to it
                d['staff_id'] = x.staff_id
                d['first_name'] = x.first_name
                d['last_name'] = x.last_name
                d['title'] = x.title
                d['title'] = x.sex
                d['email'] = x.email
                d['contact_no'] = x.contact_no
                list_emp.append(d) # Append the staff dict to the staff list
                pass  

            # Store the staff list in the result dict under key "employees"                 
            result['staffs'] = list_emp
            
        return result # return the result as a dictionary
    """
    This function shows all the flight ids available in the database 
    """
    def find_ids(self, session):
        """
        This is a special method similar to find_all but returns employee_ids only, 
        not the full details
        """

        # Print info for debugging
        print("\nFinding all staff ids ...")

        # Create a blank dictionary to return the result
        result = {}
 
        # Get the list of employees from the database
        rows = session.query(Staff).all()

        if not rows:
            result['message'] = "No employees found!"
        else:
            # Convert list of Alchemy objects to a list of dictionaries
            list_ids = []
            for x in rows:
                list_ids.append(x.staff_id)
                pass               

            # Store the list of ids in the result dict under key "employee_ids"
            result['staff_ids'] = list_ids
        
        return result # return the result as a dictionary
    
    """
    This function updates selected staff in the database
    """
    def update(self, session, staff_id, data):
    
        # Print info for debugging
        print("\nUpdating staff ...")
        print(staff_id)
        print(data)

        # Create a blank dictionary to return the result
        result = {}

        # Find the staff record
        # What happens if the staff is not found?
        emp = session.query(Staff).get(staff_id)

        # Need to find out which field has changed!
        # Just update all fields
        #emp.employee_id = data['employee_id'] # Not the primary key!
        emp.first_name = data['first_name']
        emp.last_name = data['last_name']
        emp.title = data['title']
        emp.sex = data['sex']
        emp.email = data['email']
        emp.contact_no = data['contact_no']

        session.commit() # Don't forget to commit 

        # Store an appropriate message in the result dict under key "message"
        result['message'] = "Staff updated!"     

        return result # return the result as a dictionary
    """
    This function deletes selected Staff in the database
    """    
    def delete(self, session, staff_id):

        print("\nDeleting Staff ...")
        print(staff_id)
    
            # Create a blank dictionary to return the result
        result = {}

        # Find the record and get the session to delete it  
        emp = session.query(Staff).get(staff_id)
        # What happens if the product is not found?         
        if emp:
            session.delete(emp)          
            session.commit()   # Don't forget to commit    

            # Store an appropriate message in the result dict under key "message"
            result['message'] = "Staff deleted"  
        else:  
            result['message'] = "Staff not found"

        return result

